### DISCUSSION TITLE
Clean-Up of options

### DISCUSSION THREAD

**Discussion by brenner-tobias** [homeassistant-apps/app-cloudflared#188] [Ideas]
Make the "path" option available to be used for additional_hosts (see [Cloudflared Documentation](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/local-management/ingress/#:~:text=not%20specify%20a-,path,-%2C%20all%20paths%20will)).

**Comment by elcajon** [comment]
I am rather against providing this as a configuration option. 
Many services do not work under a different path than root, so the questions and problems would always end up with us first.
In addition, there is already the possibility to add paths via the custom config.yml or the remote managed tunnel.

(I already thought about removing more advanced options to make the add-on more beginner friendly and to move more advanced users towards config.yml and remote managed tunnel functionalities.)

**Comment by brenner-tobias** [comment]
Very valid point, thanks for raising this. I agree that the add-on keeps getting more complicated and I also forgot about the two possibilities to either use custom config.yml or even easier a remote tunnel. I will suggest this to anyone who wants to include more advanced configurations from now on.

While we are at it: Any suggestions for config options that we should remove and only address in the documentation with the information to please use the custom config option? From my perspective, we can discuss to remove whole warp section (which from my end is so advanced, that everyone who wants to use it can also simply just use the custom config).

What do you think @elcajon?

**Reply by elcajon** [reply]
To be honest, I already migrated my tunnel to remote managed quite some time ago and since then I only use the corresponding token option. 
I suspect that Cloudflare will continue to expand in this direction. The way is also easier than creating your own config.yaml and supports the exact same functionality.

So when I look at the list of options:
```yaml
schema:
  external_hostname: str?
  tunnel_name: str?
  additional_hosts:
    - hostname: str
      service: str
      disableChunkedEncoding: bool?
  catch_all_service: str?
  nginx_proxy_manager: bool?
  quick_tunnel: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  reset_cloudflared_files: bool?
  data_folder: list(config|share|ssl)?
  custom_config: bool?
  warp_enable: bool?
  warp_routes:
    - str?
  warp_reset: bool?
  tunnel_token: str?
```


- I agree on warp_* settings. Let's remove them altogether. This can easily be set up with remote managed. 
- reset_cloudflared_files: I never understood why this is needed, simply uninstalling and reinstalling has the same effect, right?
- custom_config & data_folder: The two options make sense only when used together. The question would be how many use this option. Possibilities just like remote managed but more difficult to set up if you don't look up the options in the CF documentation.
- quick_tunnel: Nice feature but also useless if the domain is changed at every restart.
- catch_all_service: Could be established remote managed as well. I guess the integrated NPM option would be enough to offer. 

Maybe we should link a short survey regarding the used add-on options with the next release upgrade and see what kind of response we get?
