### DISCUSSION TITLE
Can't access HA locally after implementing Cloudflared tunnel

### DISCUSSION THREAD

**Discussion by tamorgen** [homeassistant-apps/app-cloudflared#231] [Q&A]
Good morning,
Last week I configured HA to be accessible remotely using the Cloudflare tunnel options. I pretty much used [Lewis’ Youtube walkthrough](https://youtu.be/xXAwT9N-7Hw), also written up on his [site 1](https://everythingsmarthome.co.uk/free-remote-access-for-home-assistant-with-cloudlfare/), except I didn’t use Freenom to register my domain, but did it all on Cloudflare.

Initially it functioned great, but then my app stopped working when connected to WiFi locally. I know this is because of an SSL issue, so I changed the URL from the local URL to the Cloudflare URL, and it still wouldn’t connect when connected to my WiFi. As soon as I turned off WiFi, it connects fine.

This obviously isn’t an ideal solution, and only works on my devices that have cellular connections, so my iMac doesn’t work through the App Store app, only through the browser, and I have to bypass all the SSL errors.

Here is the relevant section of my configuration.yaml

```
http:
  ssl_certificate: /ssl/origin.pem
  ssl_key: /ssl/cfprivkey.pem
#  ip_ban_enabled: true
#  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
```

In my configuration on Cloudflared itself, I only have the required option set:

```
additional_hosts: []
external_hostname: remote.morgenthaler-tech.org
```

In cloudflare, SSL/TLS is set to Full (strict).

What do I need to do to be able to access the site and app locally via eithter https://192.168.x.x or https://homeassistant.local:8123, and over the local network connection?

I'm running all the latest versions of HA and HACS.

Home Assistant OS 9.2
Home Assistant Core 2022.10.5
HACS 1.28.3
