### DISCUSSION TITLE
additional_hosts and MQTT

### DISCUSSION THREAD

**Discussion by ChrisKolan** [homeassistant-apps/app-cloudflared#334] [Q&A]
### The problem

Thanks for this add-on, it works very well and replaced for me the use of DuckDNS + Nginx. However, I have a problem with the connection to the MQTT server that is running in home assistant. My external PC with an MQTT client written in python is unable to initiate a connection to the MQTT server (Mosquitto broker). While connecting, I see the following exception: "[Errno 101] Network is unreachable".  From the external PC I can however ping the MQTT server with its hostname. On the Cloudflare zero trust page I can see that the tunnel is properly created and is "healthy". Also with two Routes (mqtt.host.com and host.com).

My current config looks as follows:

```
additional_hosts:
  - hostname: mqtt.host.com
    service: http://192.168.178.10:1883
external_hostname: host.com
tunnel_name: homeassistant
log_level: trace
```

On my previous system with DuckDNS + Nginx, everything worked without problems. Could I get some tips on what I can do to connect to the MQTT server using additional_hosts?

### What version of Cloudflared has the issue?

4.0.10

### What type of installation are you running?

Other

### Steps to reproduce the issue

Use additional_hosts and try to connect to MQTT server from external computer.

**Comment by elcajon** [comment]
```yaml
additional_hosts:
  - hostname: mqtt.host.com
    service: http://192.168.178.10:1883
```

I guess the problem is that you are trying to access your mqtt service via a (cloudflare-)http proxy.

Maybe this config will work (didn't check by myself)
```yaml
additional_hosts:
  - hostname: mqtt.host.com
    service: tcp://192.168.178.10:1883
```

You can also check the link below for all supported protocols:
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/local-management/ingress/#supported-protocols
