### DISCUSSION TITLE
Would it be possible to use the addon on HA as a cloudflare tunnel for docker containers?

### DISCUSSION THREAD

**Discussion by quartzbear** [homeassistant-apps/app-cloudflared#355] [Q&A] [answered]
Hi

I have had trouble installing cloudflare on docker, but managed installing it on HA much more easily.
Would it be possible to use the addon to serve as the tunnel for existing docker containers? 
I thought the idea is similar to the Adguard Home addon.

Is it possible or am I totally wrong here?

**Comment by brenner-tobias** [comment]
You can add any additional_host that you like. So for example if your docker container is running a http service, you can simply add this service and the IP in the additional_hosts array and have the proxy route your traffic. Please let me know if this makes sense and if you have any questions.

**Comment by quartzbear** [comment]
Thanks for your answer.
I seem to be doing something wrong. No matter what I put in, I get an error "Invalid list for option 'additional_hosts' in Cloudflared".
So, I have 2 more questions-
-Do docker containers use a http service by default or is it something I set up manually? 

-Is the array supposed to look like [this](https://developers.cloudflare.com/cloudflare-one/tutorials/multi-origin/#configure-cloudflared):
``` hostname: grafana.widgetcorp.tech```
    ```service: http://localhost:3000```
Or just like this:
   ```localhost:3000```

**Reply by brenner-tobias** [reply]
1. Docker containers do basically everything you tell them to do. It really depends on your use-case and what you do with them. For example a container from Nginx creates a http server, that you can then access to. So the answer is: You define wich docker container you are using / creating and what it does.
2. The array is supposed to look like this (see explanation in [documentation](https://github.com/brenner-tobias/addon-cloudflared/blob/main/cloudflared/DOCS.md#option-additional_hosts)):
```
additional_hosts:
  - hostname: "router.example.com"
    service: "http://192.168.1.1"
  - hostname: "diskstation.example.com"
    service: "https://192.168.1.2:5001"
  - hostname: "website.example.com"
    service: "http://192.168.1.3:8080"
    disableChunkedEncoding: true
```
