### DISCUSSION TITLE
How to: Tesla HTTP Proxy add-on with Cloudflare Tunnel

### DISCUSSION THREAD

**Discussion by codedesperate** [homeassistant-apps/app-cloudflared#618] [Q&A] [answered]
Hi, 
I have CGNAT, and so I am trying to set up this add-on. 
The "external home assistant hostname" part works flawless, and I can access my HA instance on ha.domain.com

I am also trying to set up the [Tesla HTTP Proxy Add-on](https://github.com/llamafilm/tesla-http-proxy-addon), which adds configuration to the [Nginx Homeassistant SSL Proxy Add-on](https://github.com/home-assistant/addons/tree/master/nginx_proxy). 

It is this service I am having trouble connecting to. After setting up this add-on and going to teslaapi.domain.com, I am getting a 502 Bad Gateway error. Like I said, ha.domain.com works just fine. 

This is my configuration for this add-on:
```
external_hostname: ha.domain.com
additional_hosts:
  - hostname: teslaapi.domain.com
    service: https://192.168.50.33
```

This is the extra code the Tesla HTTP Proxy Add-on created:
```
    server {
        server_name teslaapi.domain.com;

        ssl_certificate /ssl/fullchain.pem;
        ssl_certificate_key /ssl/privkey.pem;

        # dhparams file
        ssl_dhparam /data/dhparams.pem;

        listen 443 ssl http2;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        resolver 127.0.0.11;
        set $target c03d64a7-tesla-http-proxy;

        # temporary Flask app for initial auth
        location / {
            proxy_pass http://$target:8099;
        }

        # static public key for Tesla
        location /.well-known/appspecific/com.tesla.3p.public-key.pem {
            root /share/tesla;
            try_files /com.tesla.3p.public-key.pem =404;
        }
    }
```

I've used the Let's Encrypt Add-on for certificates. 
192.168.50.33 is my Home Assistant OS IP address. 

Besides a bunch of veth******* interfaces with IPv6 addresses, I also have the following. I am not sure if I should be using a different interface?

```
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.30.232.1  netmask 255.255.254.0  broadcast 172.30.233.255
        inet6 fe80::42:f1ff:feb1:ba10  prefixlen 64  scopeid 0x20<link>
        ether 02:42:f1:b1:ba:10  txqueuelen 0  (Ethernet)
        RX packets 18845  bytes 2793121 (2.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 15540  bytes 4192204 (3.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp0s2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.50.33  netmask 255.255.255.0  broadcast 192.168.50.255
        inet6 fe80::759f:3479:649d:ad5a  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:2e:45:91  txqueuelen 1000  (Ethernet)
        RX packets 19120651  bytes 23231587699 (21.6 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10355125  bytes 11947418424 (11.1 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

hassio: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.30.32.1  netmask 255.255.254.0  broadcast 172.30.33.255
        inet6 fe80::42:29ff:fe2f:9a91  prefixlen 64  scopeid 0x20<link>
        ether 02:42:29:2f:9a:91  txqueuelen 0  (Ethernet)
        RX packets 400342  bytes 181381746 (172.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 475127  bytes 332533382 (317.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 82311  bytes 62532325 (59.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 82311  bytes 62532325 (59.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

My configuration for the Nginx Add-On is pretty standard:
```
domain: ha.domain.com
hsts: max-age=31536000; includeSubDomains
certfile: fullchain.pem
keyfile: privkey.pem
cloudflare: false
customize:
  active: true
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf
```

I have this is configuration.yaml
```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
```  

I really hope someone can see my mistake here, or I soon won't have any hair left....

**Comment by codedesperate** [comment]
If I change the Cloudflared add-on config to http instead of https:
```
external_hostname: ha.domain.com
additional_hosts:
  - hostname: teslaapi.domain.com
    service: http://192.168.50.33
```

Then cloudflare gives me the error: "Argo Tunnel Error 1033"

*EDIT*
Took a few minutes, and now it gives the bad gateway error again, even with the HTTP config.

**Comment by codedesperate** [comment, marked as answer]
I figured it out following [this reply](https://github.com/llamafilm/tesla-http-proxy-addon/discussions/23#discussioncomment-8766929). I needed to make the internal subdomain the domain in nginx config. 

**This is how i fixed it**
First get certificates, I used the Let's Encrypt add-on. Make sure to include *.ha.domain.com.

**Let's Encrypt**
```
domains:
  - ha.domain.com
  - "*.ha.domain.com"
email: null@null.com
keyfile: privkey.pem
certfile: fullchain.pem
challenge: dns
dns:
  provider: dns-cloudflare
  cloudflare_api_token: redacted
```

**Cloudflared:**
```
external_hostname: ha.domain.com
additional_hosts:
  - hostname: tesla.domain.com
    service: https://tesla-internal.domain.com
```

**Cloudflare**
Confirm that this add-on has created two DNS records. ha.domain.com and tesla.domain.com.
Next, manually create an additional A record. tesla-internal.domain.com pointing to your local IP "192.168.xxx.xxx". (Or whatever it is).

**Nginx**
This is where I myself made the mistake. I used tesla.domain.com here, and not tesla-internal.domain.com

```
domain: tesla-internal.domain.com
hsts: max-age=31536000; includeSubDomains
certfile: fullchain.pem
keyfile: privkey.pem
cloudflare: false
customize:
  active: true
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf
```

**Tesla HTTP Proxy**
```
client_id: redacted
client_secret: redacted
domain: tesla.domain.com
regenerate_auth: false
region: Europe, Middle East, Africa
```

All of the above are Home Assistant Add-ons. 
If you have done this to the letter, it should work for you.
