### DISCUSSION TITLE
SSH Tunnel

### DISCUSSION THREAD

**Discussion by tommasomeli** [homeassistant-apps/app-cloudflared#734] [Q&A]
Hi,
I have configured the plugin for remote access to my Home Assistant instance via Cloudflare tunnel and everything works great.

The problem though is the remote ssh access. These are my configurations:

```
- hostname: home.mydomain.com
  service: http://192.168.1.16:8123
- hostname: ssh.mydomain.com
  service: ssh://192.168.1.16:22
```

Port 22 is correctly open, and the ssh connection locally works, but if I try to connect remotely to ssh.mydomain.com my request times out. 

How can I solve this?

**Comment by brenner-tobias** [comment]
Can you please share your full config? I just want to make sure everything is in the right spot, it should look something like this:

```
external_hostname: home.mydomain.com
additional_hosts:
  - hostname: ssh.mydomain.com
    service: ssh://192.168.1.16:22
```
